# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Intro
    url: /#welcome
    weight: 10
  - name: Challenges
    url: /#challenge
    weight: 20
  - name: AGORA
    url: /#agora
    weight: 30
  - name: People
    url: /#people
    weight: 40
#  - name: Projects
#    url: /#projects
#    weight: 50
  - name: Publications
    url: /#publications
    weight: 60
  - name: Data
    url: /#data
    weight: 70
  - name: Posts
    url: /#posts
    weight: 80
  - name: Events
    url: /#events
    weight: 90
  - name: Backers
    url: /#backers
    weight: 95
  - name: Contact
    url: /#contact
    weight: 100
