# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Intro
    url: /#welcome
    weight: 10
#  - name: EoI
#    url: /#eoi
#    weight: 15
  - name: Challenges
    url: /#challenge
    weight: 20
  - name: AGORA
    url: /#agora
    weight: 30
  - name: Markets
    url: /#markets
    weight: 35
  - name: Team
    url: /#people
    weight: 40
#  - name: Groups
#    url: /#project
#    weight: 50
  - name: Pubs
    url: /#publications
    weight: 60
#  - name: Data  # <--
#    url: /#data
#    weight: 70
  - name: Posts
    url: /#posts
    weight: 80
  - name: Events
    url: /#events
    weight: 90
  - name: Partners
    url: /#partners
    weight: 95
  - name: Contact
    url: /#contact
    weight: 100
